### ISSUE TITLE
probabilities for a 2x4 grid

### ISSUE THREAD

**Issue by tachou** [nneonneo/2048-ai#31]
Hi there, 

My father is obsessed with this game and was wondering if you can run your AI on a 2x4 grid instead of the full board so that he can see what the probabilities of making each tile value is with only that much space (since he says that is what you need to know to be a master player).

Thanks!

**Comment by nneonneo** [comment]
Interesting theory.

The AI is fairly specific to the 4x4 arrangement, simply because it was only ever designed for that size. However, it should not be that hard to modify the AI for a 2x4 size.

The easiest way I can think of doing this is to modify the move tables to include an "unmovable" value (e.g. using 15 to represent "unmovable" instead of 32768). Adjust the score tables to ignore the unmovable value, then modify the starting position to fill the bottom two rows with unmovable tiles. Then run the AI as usual; it will confine itself to the available tiles.

If you have a bit of programming experience, give this a go.

**Comment by nneonneo** [comment]
I had some time, so I implemented this suggestion in a branch. Give it a try. Run bin/2048.

Note that it does rather poorly; I've only seen it get 128 or 256 on such a small space.
